const TARGET_CATEGORY_DISPLAY_TYPE = {
  NONE: 'NONE',
  INCOMPATIBLE_TARGETS_ONLY: 'INCOMPATIBLE_TARGETS_ONLY',
  INCOMPATIBLE_ALL: 'INCOMPATIBLE_ALL',
  CATEGORIES: 'CATEGORIES',
  COMPATIBLE_TARGETS_ONLY: 'COMPATIBLE_TARGETS_ONLY',
  COMPATIBLE_ALL: 'COMPATIBLE_ALL',
}

export default TARGET_CATEGORY_DISPLAY_TYPE;
